version: '2.1'
services:
  database:
    build:
      context: ./database
      dockerfile: database.Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=mysql@sit
    # volumes:
      # - ./database/mysql-lib:/var/lib/mysql
      # - ./database/my.cnf:/etc/my.cnf
      # - ./database/setup/db-script-v3.1.sql:/docker-entrypoint-initdb.d/db-script-v2.sql
    restart: on-failure
    networks:
      - test-networks
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    depends_on:
      database:
          condition: service_healthy

      
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_USER=dev1
      - MYSQL_PASSWORD=dev@sit
      - MYSQL_URL=database
    networks:
      - test-networks


networks:
  test-networks:
    driver: bridge


    